name = "Australis Aeterna Core"
prefix = "AZF"
author = "Australis Aeterna Mod Team"
template = "cba"
mainprefix = "z"

[files]
include = [
    "*.dll",
    "*.so",
    "mod.cpp",
    "LICENSE",
    "meta.cpp",
    ".paa"
]

[version]
path = "addons/main/script_version.hpp"
git_hash = 0

[hemtt.launch.default]
parameters = ["-noSplash", "-skipIntro"]
workshop = [
    "450814997", # CBA_A3
    "463939057", # ACE3
    "1779063631", # ZEN
]
