name: Release
on: workflow_dispatch

jobs:
  release:
      runs-on: ubuntu-latest
      steps:
        - name: Get Variables
          id: version
          run: echo "::set-output name=version::${GITHUB_REF#refs/tags/v}"

        - name: Checkout the source code
          uses: actions/checkout@v4
        - name: Setup HEMTT
          uses: arma-actions/hemtt@v1
          with:
            annotate: false
        - name: Run HEMTT release
          run: hemtt release
        - name: Create Release Directory
          run: cd releases
          run: ls
        - name: Publish Release
          uses: softprops/action-gh-release@v1
          with:
            tag_name: v${{ steps.version.outputs.version }}
            files: releases/*{{ steps.version.outputs.version }}.zip
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
